# Stable Alpine branch; `docker compose build --pull` refreshes the base image
# within this branch without silently moving to edge.
FROM alpine:3.24

###############################################################################
# PACKAGES
###############################################################################
RUN apk add --no-cache \
    openssh \
    openssl \
    openconnect \
    dante-server \
    tinyproxy \
    xauth \
    ttf-freefont \
    nmap-ncat \
    autossh \
    ansible \
    iproute2 \
    coreutils \
    ca-certificates \
    dbus \
    dbus-x11 \
 && dbus-uuidgen --ensure=/etc/machine-id \
 && mkdir -p /var/lib/dbus \
 && ln -sf /etc/machine-id /var/lib/dbus/machine-id

###############################################################################
# RUNTIME USERS / DIRECTORIES
###############################################################################
# tinyproxy and Dante both drop to this unprivileged account after startup.
RUN addgroup -S proxyuser \
 && adduser -S -D -H -s /sbin/nologin -G proxyuser proxyuser \
 && mkdir -p \
      /root/.ssh \
      /var/run/sshd \
      /var/run/sockd \
      /var/run/tinyproxy \
 && chmod 700 /root/.ssh \
 && chown proxyuser:proxyuser \
      /var/run/sockd \
      /var/run/tinyproxy

###############################################################################
# VPNC-SCRIPT: QUIET LEGACY IPv4 ROUTE-CACHE FLUSH ERRORS
###############################################################################
# Alpine's OpenConnect depends on vpnc and uses /etc/vpnc/vpnc-script.
# Older vpnc-script variants call `ip route flush cache`; modern Linux no
# longer needs the IPv4 route-cache flush, and containers can expose the old
# /proc flush node read-only. Preserve the call but silence that harmless error.
RUN if [ -f /etc/vpnc/vpnc-script ]; then \
      awk ' \
        /route flush cache[[:space:]]*$/ { \
          print $0 " 2>/dev/null || true"; next \
        } \
        { print } \
      ' /etc/vpnc/vpnc-script > /tmp/vpnc-script \
      && cat /tmp/vpnc-script > /etc/vpnc/vpnc-script \
      && chmod 755 /etc/vpnc/vpnc-script \
      && rm -f /tmp/vpnc-script; \
    fi

###############################################################################
# SSH SERVER
###############################################################################
# Host keys are generated by run.sh at container startup, not at image build
# time, so a published image never ships one shared SSH private host key.
RUN sed -i -E \
      '/^[[:space:]#]*(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|AllowTcpForwarding|AllowAgentForwarding|GatewayPorts|X11Forwarding|Port)[[:space:]]+/d' \
      /etc/ssh/sshd_config \
 && printf '%s\n' \
      'PermitRootLogin yes' \
      'PasswordAuthentication yes' \
      'PubkeyAuthentication yes' \
      'AllowTcpForwarding yes' \
      'AllowAgentForwarding yes' \
      'GatewayPorts yes' \
      'X11Forwarding yes' \
      'Port 8223' \
      >> /etc/ssh/sshd_config

###############################################################################
# SSH AGENT ENVIRONMENT
###############################################################################
# Login shells can reuse the agent created by run.sh.
RUN printf '\n%s\n%s\n%s\n' \
      'if [ -f /root/.ssh/agent.env ]; then' \
      '  . /root/.ssh/agent.env' \
      'fi' \
      >> /etc/profile

###############################################################################
# APPLICATION FILES
###############################################################################
COPY run.sh /run.sh
COPY healthcheck.sh /usr/local/bin/healthcheck.sh

RUN chmod 755 \
      /run.sh \
      /usr/local/bin/healthcheck.sh

###############################################################################
# DOCUMENTED FIXED PORTS
###############################################################################
EXPOSE 8222 8223 8224

###############################################################################
# DOCKER HEALTH STATUS
###############################################################################
# Docker marks the container unhealthy; run.sh additionally runs the same
# check internally and terminates PID 1 after persistent failures so
# `restart: unless-stopped` can perform an actual restart.
HEALTHCHECK --interval=30s --timeout=20s --start-period=180s --retries=3 \
  CMD /usr/local/bin/healthcheck.sh || exit 1

STOPSIGNAL SIGTERM

###############################################################################
# ENTRYPOINT
###############################################################################
ENTRYPOINT ["/bin/sh", "/run.sh"]
